# Generated by Django 4.0.3 on 2023-07-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=50)),
                ('item2', models.CharField(max_length=50)),
                ('item3', models.CharField(max_length=50)),
                ('item4', models.CharField(max_length=50)),
                ('item5', models.CharField(max_length=50)),
                ('item6', models.CharField(max_length=50)),
                ('item7', models.CharField(max_length=50)),
                ('item8', models.CharField(max_length=50)),
                ('item9', models.CharField(max_length=50)),
                ('item10', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.messowner')),
            ],
        ),
    ]
