# Generated by Django 4.0.3 on 2023-07-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_messmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='item10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='item4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='item5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='item6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='item7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='item8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='item9',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
