# Generated by Django 3.2.2 on 2023-09-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_messmenu_item10_alter_messmenu_item4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='item1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='item2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='item3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
