# Generated by Django 3.2.2 on 2023-09-15 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mess',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.messowner'),
        ),
    ]
